language: php
php:
  - 5.5

before_install: php composer.phar install

script: php vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml

addons:
  code_climate:
    repo_token: 840b19b80ae8dd4e876870374104dc68034b89f189711923e0562bdd6ac21065